### ISSUE TITLE
Is the video link hardcode anywhere?

### ISSUE THREAD

**Issue by rajganeshp** [StaticMania/portio-hugo#12] opened 2020-10-02 19:08 UTC
I updated the youtube link in hero.yml, but it still plays the old video. Is it hardcoded anywhere?
when I hover over the link it shows the correct URL, but when I click it, it plays the old one. 

https://www.connectthoughts.com/

Thanks,
Raj

**Comment by AaronNBrock** [comment] 2020-10-02 22:41
Yeah, I noticed that too, let me take a look.

**Comment by AaronNBrock** [comment] 2020-10-02 22:49
It seems to be hardcoded right here:  https://github.com/StaticMania/portio-hugo/blob/master/assets/js/script.js#L168

**Comment by AaronNBrock** [comment] 2020-10-02 22:58
I've created a PR to fix it.  I'll try to keep my fork in reasonable working order if you want to use `https://github.com/AaronNBrock/portio-hugo` as your theme.

Alternatively, @rajganeshp could I have write permission to this repository so I can close my own PRs?

**Comment by rajganeshp** [comment] 2020-10-03 01:06
I don't know much about Github or development other than basic stuff. I
will wait until you push it to main repo and pull it.

Thanks,
Raj

**Comment by kausarpial** [comment] 2020-10-03 07:00
The PR from @AaronNBrock is merged. 
So you can have a pull from the master to solve the issue.
Thanks 
@rajganeshp

**Closed by kausarpial** 2020-10-03 07:00 UTC

**Comment by rajganeshp** [comment] 2020-10-03 15:34
I used submodule to pull the repository. which command should I use just to
update the themes folder?

Thanks,
Raj

**Comment by rajganeshp** [comment] 2020-10-03 15:58
I'm new to Github. I made couple of changes to local files. it's okay to
update from MASTER. It will be great if you can send the command to pull
the master to my local system. Again, I don't care about my local changes.
Below is the error I'm getting.

C:\hugo\sites\raj>git submodule update --remote themes\portio
error: Your local changes to the following files would be overwritten by
checkout:
        exampleSite/data/hero.yml
        layouts/partials/head.html
Please commit your changes or stash them before you switch branches.
Aborting
Unable to checkout '324b1f3cdb5ec660f30b7408b2b43333507ae767' in submodule
path 'themes/portio'

**Comment by rajganeshp** [comment] 2020-10-03 16:22
I figured out the way to update. But it's not playing the video correctly.
Take a look at my site: https://www.connectthoughts.com/

The URL looks correct and i can play it on a different tab.  Can you take a
look?

Raj

**Comment by AaronNBrock** [comment] 2020-10-03 18:04
@rajganeshp Did you change the youtube link to *not* use the `/embed/` url?  Take a look at: https://github.com/StaticMania/portio-hugo/pull/13#issuecomment-702993217

**Comment by rajganeshp** [comment] 2020-10-03 19:36
Still not working. Check my site and let me know if you can figure it out.
https://www.connectthoughts.com/

**Comment by rajganeshp** [comment] 2020-10-04 15:53
Interestingly it works in Mobile but not in Desktop browsers.

**Comment by AaronNBrock** [comment] 2020-10-04 16:29
Can you share a link to the repository you used to create the site as well?

**Comment by rajganeshp** [comment] 2020-10-04 16:33
I have only the public directory in github. not sure if it helps.
https://github.com/rajganeshp/website

**Comment by AaronNBrock** [comment] 2020-10-06 06:23
I'm unsure how I can further assist here since I'm unable to to reproduce your error.

It seems to be working fine on [my website](https://AaronNBrock.com/). You can also take a look at the source code for that site [here](https://github.com/aaronnbrock/AaronNBrock.com)
